version: '3.3'
services:
  ihmresult:
    build:
      context: ./
      args:
        VITE_SRVRESULT_URL: ${VITE_SRVRESULT_URL?error API URL not set}
        VITE_SRVRESULT_SOCKETIO_SUBFOLDER: ${VITE_SRVRESULT_SOCKETIO_SUBFOLDER?error API URL not set}
        VITE_SRVEXO_URL: ${VITE_SRVEXO_URL?error API URL not set}
    ports:
      - '8080:80'
